blueprint:
  name: Switch Inching
  description: Turn off switch after a duration
  domain: automation
  input:
    switch_target:
      name: Switch
      selector:
        entity:
          filter:
            domain:
              - switch
              - light
    inching_duration:
      name: Duration
      description: Time before switch automatically turn off
      default: 120
      selector:
        duration:

# restart automation to cancel overlapping effect 
# not necessary since we handle both on and off scenario but keep it here to ensure
mode: restart
max_exceeded: silent

trigger:
  - id: turn_on
    platform: state
    entity_id: !input switch_target
    from: "off"
    to: "on"
    for:
      milliseconds: 200
  - id: turn_off
    platform: state
    entity_id: !input switch_target
    from: "on"
    to: "off"
    for:
      milliseconds: 200

action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn_on
        sequence:
          - delay: !input inching_duration
          - service: homeassistant.turn_off
            target:
              entity_id: !input switch_target
